version: "3"
services:
  bridge:
    build: .
    volumes:
      - /bridge/node_modules
    env_file:
      - credentials.env
    environment:
      - REDIS_URL=redis://redis:6379
    command: yarn start
    depends_on:
      - redis
  redis:
    image: redis:alpine
